#启动参数加,网关应用类型为11,appType=1 表示通用网关，appType=11 专指 Spring Cloud Gateway，appType=12 为 Zuul 网关
csp.sentinel.app.type: 1

spring:
  application:
    name: gateway
  config:
    import:
      - nacos:gateway.yaml
      - nacos:common.yaml
      - nacos:gateway-route.yaml
      - nacos:sentinel-gateway.yaml
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      server-addr: 192.168.1.122:8848 # Nacos地址
      username: nacos
      password: 123456
      namespace: dev
      config:
        serverAddr: 192.168.1.122:8848 # Nacos地址
        username: nacos
        password: 123456
        extendKey: value
        namespace: dev
      #        name: gateway.yaml
      #        shared-configs:
      #          - data-id: common.yaml
      #          - data-id: gateway-route.yaml
      discovery:
        server-addr: 192.168.1.122:8848 # Nacos地址
        namespace: dev
logging:
  level:
    root: INFO

