management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  #允许循环依赖
  main:
    allow-circular-references: true
  application:
    name: web
  config:
    import:
      - nacos:dubbo.yaml
      - nacos:web.yaml
      - nacos:common.yaml
      - nacos:sentinel-dubbo.yaml
  cloud:
    nacos:
      server-addr: 192.168.1.122:8848 # Nacos地址
      username: nacos
      password: 123456
      namespace: dev
      config:
        server-addr: 192.168.1.122:8848 # Nacos地址
        username: nacos
        password: 123456
        namespace: dev
        name: web.yaml
        file-extension: yaml
      #        shared-configs:
      #          - data-id: common.yaml
      discovery:
        server-addr: 192.168.1.122:8848 # Nacos地址
        namespace: dev